ollama/ollama-js

- package.json
- src/index.ts
- src/interfaces.ts
- src/utils.ts
I have removed `node-fetch` in favor of the default fetch implementation or `window.fetch` making it compatible in both nodejs and the browser.
There is also the ability to pass a custom fetch method if you are in an environment where both `window.fetch` and global `fetch` is undefined such as older versions of nodejs:
```javascript
import { Ollama } from "ollama";
import fetch from "node-fetch";
const ollama = new Ollama({ fetch });
```
> Isomorphic Fetch

- package.json
- src/index.ts
As mentioned in #6, exporting a default ollama client was not possible as we rely on `window.fetch` and if it's not available an error is thrown.
This PR:
- Adds `whatwg-fetch` as a default fetch library so that there is always a fetch library available.
- Exports a default ollama client so that ollama can be used like this:
```
import ollama from 'ollama';
for await (const generateResult of ollama.generate("llama2", "Say 'Hello, World!'")) {
process.stdout.write(generateResult.response);
}
```
The other option is to lazy-load the `fetch` library, and fail when it is used, but I thought it could be better to be more consistent instead.
> use whatwg-fetch to allow default export

- src/index.ts
Closes https://github.com/ollama/ollama-js/issues/26
Closes https://github.com/ollama/ollama-js/issues/27
> fix: interfaces export

- src/index.ts
> fix: check if image is file path rather than b64

- src/index.ts
- src/interfaces.ts
Enforcing a default host is too restrictive when running Ollama through a proxy.
Added optional `proxy` flag to the config object to solve this.
> Add optional proxy flag to config

- examples/abort/abort.ts
- src/index.ts
- src/utils.ts
Allow streamable requests to be aborted, and not block Ollama.
Resolves #39
> add an abort controller

- README.md
- src/index.ts
- src/interfaces.ts
> remove username and password from interface

- .github/workflows/publish.yaml
- src/utils.ts
- src/version.ts
To match https://github.com/ollama/ollama-python/pull/58
> js lib user agent headers

- package.json
- src/browser.ts
- src/index.ts
This splits the main `Ollama` class into a base class which supports browser environments, and a subclass for full Node support. Currently the `.create()` method is only on the subclass.
To use in the browser:
```ts
import ollama from "ollama/browser";
```
Using in Node not changed at all.
It may be possible to also add support for `.create()` in the browser too but I haven't investigated much yet.
Fixes #25
Fixes #13
> Browser support via a separate export (Fixes #25)

- package-lock.json
- package.json
fix #55 #44 
use [unbuild](https://github.com/unjs/unbuild)，simple and stable enough 🥰
> build: add cjs compatibility

- src/interfaces.ts
This PR adds the following missing options to the `Options` interface.
- num_gpu
- num_gqa
- rope_frequency_base
- rope_frequency_scale
See https://github.com/ollama/ollama/blob/main/docs/api.md#request-6
> fix: add missing interface options

- src/browser.ts
[issue 89](https://github.com/ollama/ollama-js/issues/89)
Refactor the encodeImage function to fix a bug where large Uint8Arrays could cause a RangeError due to exceeding the maximum argument length of String.fromCharCode.apply. The new implementation iterates through the Uint8Array and builds the binary string manually, ensuring proper conversion for arrays of any size.
> fix: issue 89 - correct base64 encoding for Uint8Array in encodeImage function

- README.md
- src/browser.ts
- src/interfaces.ts
- mark the `embeddings()` method as deprecated, `embed()` is a drop-in replacement that also allows for batch embeddings
- the embeddings method will continue to work as expected
- document the embed method
This PR relies on the next release of Ollama.
> mark `embeddings()` method as deprecated in favor of `embed()`

- examples/tools/tools.ts
- src/interfaces.ts
- add tool calling to the api interface
- add a tool calling example
Adds support for https://github.com/ollama/ollama/pull/5284 and https://github.com/ollama/ollama/pull/5730 which will be in the next release.
> Add tool calling

- README.md
- examples/fill-in-middle/fill.ts
- src/interfaces.ts
Update fill-in-the-middle support to use the `suffix` field.
Implements: https://github.com/ollama/ollama/pull/5207
> add insert support to generate endpoint

- .npmignore
There is no need to include the `examples` directory when installing the `ollama` client since it won't be used, and the package size will be reduced by ~90KB.
> Add `examples` to `.npmignore`

- src/utils.ts
- test/index.spec.ts
I noticed that setting the host to only a port - see example below, would break the formatting and return a jumbled host `http://http:11434//127.0.0.1:11434`. I confirmed this is an issue on both Node and Deno, see attached images.
```js
const ollama = new Ollama({ host: ":11434" });
```
Wrote a quick test for the formatted and tested 19 different variants - see attached image, which confirmed the issue was only present when passing in a port to `formatHost`.
Setting `isExplicitProtocol` to `true` instead of `false` fixes this issue.
> Fix host breaking when set to only port

- .npmignore
`.github` and `.prettierrc.json` can be ignored when installing via npm, these are not needed for the package to work for the end user.
> Add `.github` and `.prettierrc.json` to `.npmignore`

- src/browser.ts
- use dynamic import to allow setting fetch without whatwg-fetch being present
When trying to vendor `ollama-js` into a basic JavaScript project I hit an issue that this import of `whatwg-fetch` not being simple to resolve. This change allows for setting the fetch library used by Ollama in an environment where `whatwg-fetch` is not present.
Example:
```
async function initOllama() {
try {
const ollamaModule = await import('/public/vendor/ollama/dist/browser.mjs');
// Create an instance of Ollama with a custom fetch implementation
const ollama = new ollamaModule.Ollama({
fetch: window.fetch
});
return ollama;
} catch (error) {
console.error('Error initializing Ollama:', error);
throw error;
}
}
```
> enable ollama-js use in an environment without whatwg

- examples/tools/tools.ts
The tool example was quite useful, but my first extension was to add a second function which leads to this suggested change.
I think it is better to handle the mapping of the args object returned to the specific argments needed in the function itself. This allows additional functions to be added by simply adding to the json desribing the available tools and the list of tools that can be called.
The example was already half way there by pulling the function from an array based on the name, but missed handling the parameters in a generic way to complete making invocation of the function generic.
> chore: small improvement to tool example

- src/browser.ts
- src/interfaces.ts
- src/utils.ts
- Allow users to add custom headers
- Prevents overriding of basic headers
- Updated interface to user `HeadersInit` instead of `Headers` -> more flexible class 
```typescript
type HeadersInit = [string, string][] | Record<string, string> | Headers
```
Checked functionality by adding logging middleware on go server locally.
Also ran some quick tests:
Closes https://github.com/ollama/ollama-js/pull/154
Closes https://github.com/ollama/ollama-js/pull/156
Shoutout to @gnpaone for getting it most of the way there!
> Custom Headers

- examples/tools/tools.ts
NYC is not an airport code, and smart models, notably Qwen, will catch this, and substitute JFK to correct the user's mistake. The the tool schema specifies that the function takes airport codes.
This can be confusing for people new to the API, since the natural reaction is that the model is broken and not the setup.
> Rename "airport code" NYC to LGA (LaGuardia) in examples/tools

- README.md
- src/interfaces.ts
The Ollama API accepts a Go `time.Duration` as the `keep_alive` time parameter. Its not clearly documented anywhere how it expects the duration to be formatted, and the default behavior (numbers are seconds) is not expected. Adding documentation around this to make it easier to use `keep_alive`.
Resolves #81
> docs: specify the format for keep_alive duration

- README.md
- src/browser.ts
- src/index.ts
- src/interfaces.ts
Add new create API structure, remove broken file streaming logic
- Updates CreateRequest interface with new fields
- Removes broken logic for streaming model creation from local files
- Previous implementation did not properly handle file streams
- Model creation from files should be handled by separate PR
- Updates documentation and types to reflect new API structure
Follow-up: https://github.com/ollama/ollama-js/issues/191
> update create api for v0.5.5 and deprecate create from files

- src/index.ts
Fixes #187 issue by just exporting `AbortableAsyncIterator` class as type from `src/index.ts` file.
> Export `AbortableAsyncIterator` class as type

- README.md
This got missed during API updates.
> docs: remove create example from README

- package-lock.json
- package.json
- src/browser.ts
- src/constant.ts
- src/defaultHost.ts
- src/utils.ts
- test/index.test.ts
The default host `http://127.0.0.1:11434` is hard-coded in multiple places, 
So, Put it in one variable in a central place (`src/defaultHost.ts` file) and then reuse it in those places.
> refactor: put the default host in a variable and then reuse it

- src/index.ts
Fix: Use `node:` prefix for built-in modules
This pull request updates the import statements for the `fs` and `path` modules to use the `node:` prefix. This is the recommended modern way to import Node.js core modules and improves code clarity, prevents potential naming conflicts, and enhances future compatibility.  It also can sometimes help with tree-shaking in bundlers.
Specifically, the following changes were made:
* `import fs, { promises } from 'fs'` changed to `import fs, { promises } from 'node:fs'`
* `import { resolve } from 'path'` changed to `import { resolve } from 'node:path'`
This change ensures that the code explicitly imports the built-in Node.js modules and avoids any ambiguity.  It's a best practice for maintainable and robust Node.js code.
> Fix: Use node: prefix for built-in modules

- src/interfaces.ts
Minor thing, I noticed when listing the models via `ollama.list()` the `models` within the response value is of type `ModelResponse` and that the json returned has a field of `model` but the interface doesn't. You can see the output to doing `ollama.list` below.
Code:
```ts
import { Ollama } from './src/index'
const ollama = new Ollama()
const models = await ollama.list()
console.log(models)
```
Output:
```sh
ollama-js [ main][!][📦 v0.0.0][ v22.9.0]
❯ bun main.ts 
{
models: [
{
name: "qwen2.5-coder:14b",
model: "qwen2.5-coder:14b",
modified_at: "2025-01-04T20:56:34.562706389Z",
size: 8988124256,
digest: "3028237cc8c52fea4e77185d72cc997b2e90392791f7c82fe1c71995d56e642d",
details: [Object ...],
}, {
name: "opencoder:latest",
model: "opencoder:latest",
modified_at: …
```
> feat: add string model field to the ModelResponse interface

- examples/fill-in-middle/fill.ts
- examples/multimodal/multimodal.ts
- examples/pull-progress/pull.ts
Fix top-level await issue: All examples use proper async/await patterns wrapped in functions with error handling.
After the fix,  I can run the case in the example:
related issue: [issue 205](https://github.com/ollama/ollama-js/issues/205)
> fix: fix top await in examples

- src/utils.ts
- test/utils.test.ts
**Description:**  
This pull request addresses an issue where filtering custom headers using `Object.entries(options.headers)` fails when the headers are not provided as a plain object (for example, when using a `Headers` instance or an array of key-value pairs).  
**Changes Introduced:**  
- Added a new utility function `normalizeHeaders` that converts any valid `HeaderInit` (i.e. a `Headers` instance, an array of key-value pairs, or a plain object) into a plain object.
- Updated the custom header filtering logic to work reliably by first normalizing `options.headers` before filtering out the default headers.
- Included JSDoc documentation for the `normalizeHeaders` function.
**Testing & Impact:**  
- Manually verified that the new implementation correctly processes different header …
> fix: Normalize header handling for all HeaderInit types

- .github/workflows/test.yaml
The upload-artifact job v3 is deprecated, updating to v4 so jobs continue to run.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> workflows: update upload artifact job to v4

- src/utils.ts
Adding a fallback for the [now deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform) `window.navigator.platform`.
The best alternative seems to be [to use`window.navigator.userAgentData.platform`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData).
Mentioned in https://github.com/ollama/ollama-js/issues/182
I didn't find much contribution guide, so let me know if you need me to give more information.
> Fallback for deprecated `window.navigator.platform`

- src/interfaces.ts
After https://github.com/ollama/ollama/pull/5709 (Docs updated in https://github.com/ollama/ollama/pull/6079), requests to the `/embed` endpoint return "metrics" properties including:
* `total_duration`
* `load_duration`
* `prompt_eval_count`
This PR simply adds them to to the `EmbedResponse` type for consistency with Ollama's API.
> Add missing response properties for `EmbedResponse`

- src/utils.ts
- test/index.test.ts
This pull request adds support for Basic Authentication in the formatHost function by including username and password from the input URL into the formatted result.
Ollama does not provide built-in security or authentication mechanisms. To protect access to the service—especially in shared or production environments—many users set up a reverse proxy like Nginx to enforce Basic Authentication.
For example:
```nginx
http {
server {
listen 80;
auth_basic "Restricted";
auth_basic_user_file /etc/nginx/.htpasswd;
location / {
proxy_pass http://localhost:11434;
}
}
}
```
With this configuration, requests to Ollama require valid credentials. In order for clients to successfully communicate through the reverse proxy, they must include credentials in the request URL (e.g., …
> fix(formatHost): support basic auth in host URL

- README.md
- examples/README.md
- examples/thinking/thinking-enabled.ts
- examples/thinking/thinking-streaming.ts
- src/interfaces.ts
Changes to support https://github.com/ollama/ollama/pull/10584
> add thinking support and examples
